## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
new_application_df = application_df.drop(columns=["EIN", "NAME"])

new_application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,142590,1

In [3]:
# Determine the number of unique values in each column.
new_application_df.nunique(axis=0)

APPLICATION_TYPE      17
AFFILIATION            6
CLASSIFICATION        71
USE_CASE               5
ORGANIZATION           4
STATUS                 2
INCOME_AMT             9
ASK_AMT             8747
IS_SUCCESSFUL          2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
AT_value_counts = new_application_df["APPLICATION_TYPE"].value_counts()
AT_value_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
AT_value_count_limit = 200
application_types_to_replace = AT_value_counts[AT_value_counts < AT_value_count_limit].index.tolist()
application_types_to_replace
# Replace in dataframe
for app in application_types_to_replace:
    new_application_df['APPLICATION_TYPE'] = new_application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
new_application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
C_value_counts = new_application_df['CLASSIFICATION'].value_counts()
C_value_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
C_value_counts[C_value_counts.values>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
C_value_count_limit = 101
classifications_to_replace = C_value_counts[C_value_counts < C_value_count_limit].index.tolist()
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    new_application_df['CLASSIFICATION'] = new_application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
new_application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [10]:
# Look at CLASSIFICATION value counts for binning
AA_value_counts = new_application_df['ASK_AMT'].value_counts()
AA_value_counts

5000        25398
10478           3
15583           3
63981           3
6725            3
            ...
5371754         1
30060           1
43091152        1
18683           1
36500179        1
Name: ASK_AMT, Length: 8747, dtype: int64

In [11]:
AA_value_counts[AA_value_counts.values>100]

5000    25398
Name: ASK_AMT, dtype: int64

In [18]:
application_df['ASK_AMT'].max()

8597806340

In [17]:
len(application_df[application_df['ASK_AMT'] > 100000000])

101

In [22]:
# Create the bins in which Data will be held

bins = [0, 5001, 50000, 100000, 500000, 1000000,20000000, 10000000000]

# Create the names for the five bins
group_names = ["5k", "50k", "100k", "500k", "1m","20m","over 20m"]

In [23]:
new_application_df["binned_ASK_AMT"]= pd.cut(new_application_df['ASK_AMT'], bins, labels=group_names, include_lowest=True)
new_application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL,binned_ASK_AMT
0,T10,Independent,C1000,ProductDev,Association,1,0,5000,1,5k
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,108590,1,500k
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,5000,0,5k
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,6692,1,50k
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,142590,1,500k
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,5000,0,5k
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,5000,0,5k
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,5000,0,5k
34297,T5,Independent,C3000,ProductDev,Association,1,0,5000,1,5k
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,36500179,0,over 20m

In [24]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
new_application_df = new_application_df.drop(columns=["ASK_AMT"])

In [33]:
new_application_df.nunique(axis=0)

APPLICATION_TYPE     9
AFFILIATION          6
CLASSIFICATION      12
USE_CASE             5
ORGANIZATION         4
STATUS               2
INCOME_AMT           9
IS_SUCCESSFUL        2
binned_ASK_AMT       7
dtype: int64

In [25]:
# Convert categorical data to numeric with `pd.get_dummies`
new_application_dummies_df = pd.get_dummies(new_application_df)
new_application_dummies_df.head()

,STATUS,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,binned_ASK_AMT_5k,binned_ASK_AMT_50k,binned_ASK_AMT_100k,binned_ASK_AMT_500k,binned_ASK_AMT_1m,binned_ASK_AMT_20m,binned_ASK_AMT_over 20m
0,1,1,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,1,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
3,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [26]:
# Split our preprocessed data into our features and target arrays
X = new_application_dummies_df.drop('IS_SUCCESSFUL', axis=1).values
y = new_application_dummies_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [27]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [28]:
X_train[1]

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

## Compile, Train and Evaluate the Model

In [29]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

model = tf.keras.models.Sequential()

# First hidden layer
model.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
model.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 8)                 432

 dense_1 (Dense)             (None, 5)                 45

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 483
Trainable params: 483
Non-trainable params: 0
_________________________________________________________________

In [30]:
# Compile the model
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [31]:
# Train the model
fit_model = model.fit(X_train_scaled,y_train,epochs=40)

Epoch 1/40
804/804 [==============================] - 1s 1ms/step - loss: 0.6271 - accuracy: 0.6984
Epoch 2/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5749 - accuracy: 0.7279
Epoch 3/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5598 - accuracy: 0.7296
Epoch 4/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5545 - accuracy: 0.7308
Epoch 5/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5524 - accuracy: 0.7306
Epoch 6/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5510 - accuracy: 0.7315
Epoch 7/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5499 - accuracy: 0.7306
Epoch 8/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5491 - accuracy: 0.7319
Epoch 9/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7310
Epoch 10/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7320
Epoch 11/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7320
Epoch 12/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7322
Epoch 13/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7329
Epoch 14/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7322
Epoch 15/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5454 - accuracy: 0.7324
Epoch 16/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5450 - accuracy: 0.7325
Epoch 17/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5450 - accuracy: 0.7319
Epoch 18/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7322
Epoch 19/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7318
Epoch 20/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7329
Epoch 21/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7324
Epoch 22/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7321
Epoch 23/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7321
Epoch 24/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7325
Epoch 25/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7325
Epoch 26/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7328
Epoch 27/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7332
Epoch 28/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7320
Epoch 29/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7328
Epoch 30/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7320
Epoch 31/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7323
Epoch 32/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7322
Epoch 33/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7327
Epoch 34/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7327
Epoch 35/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7327
Epoch 36/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7334
Epoch 37/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7330
Epoch 38/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7327
Epoch 39/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7331
Epoch 40/40
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7329

In [32]:
# Evaluate the model using the test data
model_loss, model_accuracy = model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5518 - accuracy: 0.7259 - 362ms/epoch - 1ms/step
Loss: 0.5518048405647278, Accuracy: 0.7259474992752075

In [ ]:
# Export our model to HDF5 file
model.save('AlphabetSoupCharity.h5')

# OPTIMISATION

# activation method change

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

model2 = tf.keras.models.Sequential()

# First hidden layer
model2.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
model2.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="tanh"))

# Output layer
model2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
model2.summary()

In [ ]:
# Compile the model
model2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
fit_model = model2.fit(X_train_scaled,y_train,epochs=100)

In [ ]:
# Evaluate the model using the test data
model2_loss, model2_accuracy = model2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model2_loss}, Accuracy: {model2_accuracy}")

# Increase in hidden_nodes_layer

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  16
hidden_nodes_layer2 = 10

model3 = tf.keras.models.Sequential()

# First hidden layer
model3.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
model3.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
model3.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
model3.summary()

In [ ]:
# Compile the model
model3.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
fit_model = model3.fit(X_train_scaled,y_train,epochs=100)

In [ ]:
# Evaluate the model using the test data
model3_loss, model3_accuracy = model3.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model3_loss}, Accuracy: {model3_accuracy}")

# Further changes

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  16
hidden_nodes_layer2 = 10

model4 = tf.keras.models.Sequential()

# First hidden layer
model4.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="sigmoid")
)

# Second hidden layer
model4.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

# Output layer
model4.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
model4.summary()

# Compile the model
model4.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = model4.fit(X_train_scaled,y_train,epochs=100)

# Evaluate the model using the test data
model4_loss, model4_accuracy = model4.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model4_loss}, Accuracy: {model4_accuracy}")

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  35
hidden_nodes_layer2 = 25
hidden_nodes_layer3 = 15
hidden_nodes_layer4 = 10
model5 = tf.keras.models.Sequential()

# First hidden layer
model5.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
model5.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))
model5.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))
model5.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="relu"))
# Output layer
model5.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
model5.summary()

# Compile the model
model5.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = model5.fit(X_train_scaled,y_train,epochs=100)

# Evaluate the model using the test data
model5_loss, model5_accuracy = model5.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model5_loss}, Accuracy: {model5_accuracy}")

In [36]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  16
hidden_nodes_layer2 = 21
hidden_nodes_layer3 = 26
hidden_nodes_layer4 = 11
model6 = tf.keras.models.Sequential()

# First hidden layer
model6.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
model6.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))
model6.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))
model6.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="relu"))
# Output layer
model6.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
model6.summary()

# Compile the model
model6.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = model6.fit(X_train_scaled,y_train,epochs=100)

# Evaluate the model using the test data
model6_loss, model6_accuracy = model6.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model6_loss}, Accuracy: {model6_accuracy}")

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_15 (Dense)            (None, 16)                864

 dense_16 (Dense)            (None, 21)                357

 dense_17 (Dense)            (None, 26)                572

 dense_18 (Dense)            (None, 11)                297

 dense_19 (Dense)            (None, 1)                 12

=================================================================
Total params: 2,102
Trainable params: 2,102
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.5811 - accuracy: 0.7119
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5543 - accuracy: 0.7273
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5501 - accuracy: 0.7300
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7307
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7324
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5457 - accuracy: 0.7315
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7320
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5433 - accuracy: 0.7348
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7318
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7341
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7341
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7335
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7345
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7347
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5400 - accuracy: 0.7352
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7346
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7345
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7361
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7367
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7355
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7368
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5376 - accuracy: 0.7363
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7358
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7372
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5364 - accuracy: 0.7372
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5363 - accuracy: 0.7388
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7373
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7370
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5356 - accuracy: 0.7393
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7395
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5354 - accuracy: 0.7383
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5351 - accuracy: 0.7370
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7382
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7383
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7393
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7387
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5339 - accuracy: 0.7383
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5338 - accuracy: 0.7395
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7391
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7397
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5331 - accuracy: 0.7390
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7397
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7394
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7407
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7411
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7410
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5322 - accuracy: 0.7395
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7404
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7398
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7401
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7407
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7405
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7397
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7404
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5308 - accuracy: 0.7401
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5308 - accuracy: 0.7415
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5308 - accuracy: 0.7413
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5311 - accuracy: 0.7412
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5307 - accuracy: 0.7409
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5306 - accuracy: 0.7401
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5300 - accuracy: 0.7405
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5306 - accuracy: 0.7407
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5300 - accuracy: 0.7409
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7411
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5304 - accuracy: 0.7416
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7413
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5296 - accuracy: 0.7407
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5296 - accuracy: 0.7408
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5298 - accuracy: 0.7411
Epoch 70/100

804/804 [==============================] - 1s 1ms/step - loss: 0.5287 - accuracy: 0.7424
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5297 - accuracy: 0.7416
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5293 - accuracy: 0.7417
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5286 - accuracy: 0.7414
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5288 - accuracy: 0.7413
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5290 - accuracy: 0.7425
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5290 - accuracy: 0.7410
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5289 - accuracy: 0.7417
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5286 - accuracy: 0.7418
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5286 - accuracy: 0.7424
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5279 - accuracy: 0.7427
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5281 - accuracy: 0.7413
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5288 - accuracy: 0.7426
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5276 - accuracy: 0.7410
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5279 - accuracy: 0.7418
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5277 - accuracy: 0.7425
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5281 - accuracy: 0.7421
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5275 - accuracy: 0.7430
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5277 - accuracy: 0.7428
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5271 - accuracy: 0.7427
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5279 - accuracy: 0.7420
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5275 - accuracy: 0.7414
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5269 - accuracy: 0.7424
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5271 - accuracy: 0.7428
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5275 - accuracy: 0.7418
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5266 - accuracy: 0.7417
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5270 - accuracy: 0.7426
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5274 - accuracy: 0.7415
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5272 - accuracy: 0.7417
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5269 - accuracy: 0.7421
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5265 - accuracy: 0.7418
268/268 - 1s - loss: 0.5655 - accuracy: 0.7236 - 695ms/epoch - 3ms/step
Loss: 0.5654547214508057, Accuracy: 0.7236151695251465

In [37]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  16
hidden_nodes_layer2 = 21
hidden_nodes_layer3 = 26
hidden_nodes_layer4 = 11
hidden_nodes_layer5 = 21
model7 = tf.keras.models.Sequential()

# First hidden layer
model7.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
model7.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))
model7.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))
model7.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="relu"))
model7.add(tf.keras.layers.Dense(units=hidden_nodes_layer5, activation="relu"))
# Output layer
model7.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))


# Check the structure of the model
model7.summary()

# Compile the model
model7.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = model7.fit(X_train_scaled,y_train,epochs=20)

# Evaluate the model using the test data
model7_loss, model7_accuracy = model7.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model7_loss}, Accuracy: {model7_accuracy}")

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_20 (Dense)            (None, 16)                864

 dense_21 (Dense)            (None, 21)                357

 dense_22 (Dense)            (None, 26)                572

 dense_23 (Dense)            (None, 11)                297

 dense_24 (Dense)            (None, 21)                252

 dense_25 (Dense)            (None, 1)                 22

=================================================================
Total params: 2,364
Trainable params: 2,364
Non-trainable params: 0
_________________________________________________________________
Epoch 1/20
804/804 [==============================] - 2s 1ms/step - loss: 0.5834 - accuracy: 0.7073
Epoch 2/20
804/804 [==============================] - 1s 2ms/step - loss: 0.5561 - accuracy: 0.7284
Epoch 3/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5523 - accuracy: 0.7308
Epoch 4/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5505 - accuracy: 0.7301
Epoch 5/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7336
Epoch 6/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5468 - accuracy: 0.7328
Epoch 7/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5461 - accuracy: 0.7337
Epoch 8/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7337
Epoch 9/20
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7340
Epoch 10/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7341
Epoch 11/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7343
Epoch 12/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7351
Epoch 13/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7346
Epoch 14/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7351
Epoch 15/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7355
Epoch 16/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7352
Epoch 17/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7355
Epoch 18/20
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7357
Epoch 19/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7347
Epoch 20/20
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7376
268/268 - 0s - loss: 0.5549 - accuracy: 0.7313 - 358ms/epoch - 1ms/step
Loss: 0.5548951029777527, Accuracy: 0.7313119769096375

In [ ]:
# Export our model to HDF5 file
model.save('AlphabetSoupCharity_Optimisation.h5')

In [35]:
# Define the number of units for each layer
units = [16, 21, 26, 11, 21]

# Create a sequential model
modelNEW = tf.keras.models.Sequential()

# Add the first layer
modelNEW.add(tf.keras.layers.Dense(units[0], activation='relu', input_shape=(10,)))

# Add the remaining hidden layers
for i in range(1, len(units)):
    modelNEW.add(tf.keras.layers.Dense(units[i], activation='relu'))

# Add the output layer
modelNEW.add(tf.keras.layers.Dense(1, activation='sigmoid'))

# Compile the model
modelNEW.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
modelNEW.fit(X_train_scaled, y_train, epochs=10, batch_size=32)

Epoch 1/10

ValueError: in user code:

    File "D:\anaconda3\lib\site-packages\keras\engine\training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "D:\anaconda3\lib\site-packages\keras\engine\training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "D:\anaconda3\lib\site-packages\keras\engine\training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "D:\anaconda3\lib\site-packages\keras\engine\training.py", line 993, in train_step
        y_pred = self(x, training=True)
    File "D:\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "D:\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential_2" is incompatible with the layer: expected shape=(None, 10), found shape=(None, 53)